name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
